{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "f8172718",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'\\nWhen creating a custom exception in Python, it is recommended to inherit from the Exception class or one of its subclasses, as this provides a number of important features and benefits:\\n\\nStandardized behavior: By inheriting from the Exception class, your custom exception will have the same basic behavior as all other built-in exceptions, including the ability to be raised, caught, and printed with a traceback.\\n\\nCompatibility with existing code: Many existing Python libraries and frameworks are designed to work with exceptions that inherit from the built-in Exception class. By following this convention, you can ensure that your custom exception will be compatible with these libraries and frameworks.\\n\\nCustomization: By creating a custom exception that inherits from the Exception class, you can add your own attributes and methods to the exception object. This can be useful for providing additional information about the exception or for customizing the behavior of the exception.\\n\\nClarity and readability: By using the Exception class as the base class for your custom exception, you make it clear to other developers that your object is intended to be used as an exception. This can make your code more readable and easier to understand.\\n'"
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#ANSWER 1-\n",
    "\"\"\"\n",
    "When creating a custom exception in Python, it is recommended to inherit from the Exception class or one of its subclasses, as this provides a number of important features and benefits:\n",
    "\n",
    "Standardized behavior: By inheriting from the Exception class, your custom exception will have the same basic behavior as all other built-in exceptions, including the ability to be raised, caught, and printed with a traceback.\n",
    "\n",
    "Compatibility with existing code: Many existing Python libraries and frameworks are designed to work with exceptions that inherit from the built-in Exception class. By following this convention, you can ensure that your custom exception will be compatible with these libraries and frameworks.\n",
    "\n",
    "Customization: By creating a custom exception that inherits from the Exception class, you can add your own attributes and methods to the exception object. This can be useful for providing additional information about the exception or for customizing the behavior of the exception.\n",
    "\n",
    "Clarity and readability: By using the Exception class as the base class for your custom exception, you make it clear to other developers that your object is intended to be used as an exception. This can make your code more readable and easier to understand.\n",
    "\"\"\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "189637db",
   "metadata": {},
   "outputs": [],
   "source": [
    "#ANSWER 2-\n",
    "def print_exception_hierarchy():\n",
    "    \"\"\"\n",
    "    Prints the Python exception hierarchy.\n",
    "    \"\"\"\n",
    "    base_exceptions = [\n",
    "        BaseException,\n",
    "        SystemExit,\n",
    "        KeyboardInterrupt,\n",
    "        GeneratorExit,\n",
    "        Exception,\n",
    "    ]\n",
    "    for exc_type in base_exceptions:\n",
    "        print(f\"{exc_type.__name__}\")\n",
    "        for sub_exc_type in exc_type.__subclasses__():\n",
    "            print(f\"\\t{sub_exc_type.__name__}\")\n",
    "            for sub_sub_exc_type in sub_exc_type.__subclasses__():\n",
    "                print(f\"\\t\\t{sub_sub_exc_type.__name__}\")\n",
    "                # continue recursively for sub-sub-exceptions and so on...\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "d32b8a13",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "BaseException\n",
      "\tException\n",
      "\t\tTypeError\n",
      "\t\tStopAsyncIteration\n",
      "\t\tStopIteration\n",
      "\t\tImportError\n",
      "\t\tOSError\n",
      "\t\tEOFError\n",
      "\t\tRuntimeError\n",
      "\t\tNameError\n",
      "\t\tAttributeError\n",
      "\t\tSyntaxError\n",
      "\t\tLookupError\n",
      "\t\tValueError\n",
      "\t\tAssertionError\n",
      "\t\tArithmeticError\n",
      "\t\tSystemError\n",
      "\t\tReferenceError\n",
      "\t\tMemoryError\n",
      "\t\tBufferError\n",
      "\t\tWarning\n",
      "\t\tError\n",
      "\t\t_OptionError\n",
      "\t\terror\n",
      "\t\tVerbose\n",
      "\t\t_Error\n",
      "\t\tSubprocessError\n",
      "\t\tTokenError\n",
      "\t\tStopTokenizing\n",
      "\t\tClassFoundException\n",
      "\t\tEndOfBlock\n",
      "\t\tTraitError\n",
      "\t\tError\n",
      "\t\tError\n",
      "\t\t_GiveupOnSendfile\n",
      "\t\terror\n",
      "\t\tIncomplete\n",
      "\t\tTimeoutError\n",
      "\t\tInvalidStateError\n",
      "\t\tLimitOverrunError\n",
      "\t\tQueueEmpty\n",
      "\t\tQueueFull\n",
      "\t\terror\n",
      "\t\tLZMAError\n",
      "\t\tRegistryError\n",
      "\t\t_GiveupOnFastCopy\n",
      "\t\tEmpty\n",
      "\t\tFull\n",
      "\t\tZMQBaseError\n",
      "\t\tPickleError\n",
      "\t\t_Stop\n",
      "\t\tArgumentError\n",
      "\t\tArgumentTypeError\n",
      "\t\tConfigError\n",
      "\t\tConfigurableError\n",
      "\t\tApplicationError\n",
      "\t\tTimeoutError\n",
      "\t\tCOMError\n",
      "\t\tArgumentError\n",
      "\t\tReturnValueIgnoredError\n",
      "\t\tKeyReuseError\n",
      "\t\tUnknownKeyError\n",
      "\t\tLeakedCallbackError\n",
      "\t\tBadYieldError\n",
      "\t\tReturnValueIgnoredError\n",
      "\t\tReturn\n",
      "\t\tInvalidPortNumber\n",
      "\t\tNoIPAddresses\n",
      "\t\tBadZipFile\n",
      "\t\tLargeZipFile\n",
      "\t\tError\n",
      "\t\tBadEntryPoint\n",
      "\t\tNoSuchEntryPoint\n",
      "\t\tDuplicateKernelError\n",
      "\t\tErrorDuringImport\n",
      "\t\tBdbQuit\n",
      "\t\tRestart\n",
      "\t\tFindCmdError\n",
      "\t\tHomeDirError\n",
      "\t\tProfileDirError\n",
      "\t\tIPythonCoreError\n",
      "\t\tInputRejected\n",
      "\t\tGetoptError\n",
      "\t\tOptionError\n",
      "\t\tErrorToken\n",
      "\t\tPrefilterError\n",
      "\t\tAliasError\n",
      "\t\tError\n",
      "\t\tWarning\n",
      "\t\tSpaceInInput\n",
      "\t\tDOMException\n",
      "\t\tValidationError\n",
      "\t\tEditReadOnlyBuffer\n",
      "\t\t_Retry\n",
      "\t\tInvalidLayoutError\n",
      "\t\tHeightIsUnknownError\n",
      "\t\tParserSyntaxError\n",
      "\t\tInternalParseError\n",
      "\t\t_PositionUpdatingFinished\n",
      "\t\tSimpleGetItemNotFound\n",
      "\t\tUncaughtAttributeError\n",
      "\t\tHasNoContext\n",
      "\t\tParamIssue\n",
      "\t\t_JediError\n",
      "\t\tOnErrorLeaf\n",
      "\t\tInvalidPythonEnvironment\n",
      "\t\tMessageError\n",
      "\t\tError\n",
      "\t\tHTTPException\n",
      "\t\tInteractivelyDefined\n",
      "\t\tKillEmbedded\n",
      "\t\tError\n",
      "\t\tError\n",
      "\t\tTimeoutExpired\n",
      "\t\tTimeoutAbandoned\n",
      "\t\tQueueEmpty\n",
      "\t\tQueueFull\n",
      "\t\tExpatError\n",
      "\t\tError\n",
      "\t\terror\n",
      "\t\tcom_error\n",
      "\t\tinternal_error\n",
      "\t\tParseBaseException\n",
      "\t\tRecursiveGrammarException\n",
      "\t\tResolutionError\n",
      "\t\tUnableToResolveVariableException\n",
      "\t\tInvalidTypeInArgsException\n",
      "\tGeneratorExit\n",
      "\tSystemExit\n",
      "\tKeyboardInterrupt\n",
      "\tCancelledError\n",
      "\tDebuggerInitializationError\n",
      "\tAbortThread\n",
      "SystemExit\n",
      "KeyboardInterrupt\n",
      "GeneratorExit\n",
      "Exception\n",
      "\tTypeError\n",
      "\t\tFloatOperation\n",
      "\t\tMultipartConversionError\n",
      "\tStopAsyncIteration\n",
      "\tStopIteration\n",
      "\tImportError\n",
      "\t\tModuleNotFoundError\n",
      "\t\tZipImportError\n",
      "\tOSError\n",
      "\t\tConnectionError\n",
      "\t\tBlockingIOError\n",
      "\t\tChildProcessError\n",
      "\t\tFileExistsError\n",
      "\t\tFileNotFoundError\n",
      "\t\tIsADirectoryError\n",
      "\t\tNotADirectoryError\n",
      "\t\tInterruptedError\n",
      "\t\tPermissionError\n",
      "\t\tProcessLookupError\n",
      "\t\tTimeoutError\n",
      "\t\tUnsupportedOperation\n",
      "\t\therror\n",
      "\t\tgaierror\n",
      "\t\ttimeout\n",
      "\t\tSSLError\n",
      "\t\tError\n",
      "\t\tSpecialFileError\n",
      "\t\tExecError\n",
      "\t\tReadError\n",
      "\t\tURLError\n",
      "\t\tBadGzipFile\n",
      "\tEOFError\n",
      "\t\tIncompleteReadError\n",
      "\tRuntimeError\n",
      "\t\tRecursionError\n",
      "\t\tNotImplementedError\n",
      "\t\t_DeadlockError\n",
      "\t\tBrokenBarrierError\n",
      "\t\tBrokenExecutor\n",
      "\t\tSendfileNotAvailableError\n",
      "\t\tExtractionError\n",
      "\t\tVariableError\n",
      "\tNameError\n",
      "\t\tUnboundLocalError\n",
      "\tAttributeError\n",
      "\t\tFrozenInstanceError\n",
      "\tSyntaxError\n",
      "\t\tIndentationError\n",
      "\tLookupError\n",
      "\t\tIndexError\n",
      "\t\tKeyError\n",
      "\t\tCodecRegistryError\n",
      "\tValueError\n",
      "\t\tUnicodeError\n",
      "\t\tUnsupportedOperation\n",
      "\t\tJSONDecodeError\n",
      "\t\tSSLCertVerificationError\n",
      "\t\tError\n",
      "\t\tIllegalMonthError\n",
      "\t\tIllegalWeekdayError\n",
      "\t\tParserError\n",
      "\t\tClassNotFound\n",
      "\t\tClipboardEmpty\n",
      "\t\tMessageDefect\n",
      "\t\tMacroToEdit\n",
      "\t\tInvalidFileException\n",
      "\t\tUnequalIterablesError\n",
      "\t\tInvalidVersion\n",
      "\t\t_InvalidELFFileHeader\n",
      "\t\tInvalidWheelFilename\n",
      "\t\tInvalidSdistFilename\n",
      "\t\tInvalidSpecifier\n",
      "\t\tInvalidMarker\n",
      "\t\tUndefinedComparison\n",
      "\t\tUndefinedEnvironmentName\n",
      "\t\tInvalidRequirement\n",
      "\t\tInvalidVersion\n",
      "\tAssertionError\n",
      "\tArithmeticError\n",
      "\t\tFloatingPointError\n",
      "\t\tOverflowError\n",
      "\t\tZeroDivisionError\n",
      "\t\tDecimalException\n",
      "\tSystemError\n",
      "\t\tCodecRegistryError\n",
      "\tReferenceError\n",
      "\tMemoryError\n",
      "\tBufferError\n",
      "\tWarning\n",
      "\t\tUserWarning\n",
      "\t\tDeprecationWarning\n",
      "\t\tPendingDeprecationWarning\n",
      "\t\tSyntaxWarning\n",
      "\t\tRuntimeWarning\n",
      "\t\tFutureWarning\n",
      "\t\tImportWarning\n",
      "\t\tUnicodeWarning\n",
      "\t\tBytesWarning\n",
      "\t\tResourceWarning\n",
      "\t\tDeprecatedTzFormatWarning\n",
      "\t\tPkgResourcesDeprecationWarning\n",
      "\tError\n",
      "\t_OptionError\n",
      "\terror\n",
      "\tVerbose\n",
      "\t_Error\n",
      "\tSubprocessError\n",
      "\t\tCalledProcessError\n",
      "\t\tTimeoutExpired\n",
      "\tTokenError\n",
      "\tStopTokenizing\n",
      "\tClassFoundException\n",
      "\tEndOfBlock\n",
      "\tTraitError\n",
      "\tError\n",
      "\tError\n",
      "\t\tCancelledError\n",
      "\t\tTimeoutError\n",
      "\t\tInvalidStateError\n",
      "\t_GiveupOnSendfile\n",
      "\terror\n",
      "\tIncomplete\n",
      "\tTimeoutError\n",
      "\tInvalidStateError\n",
      "\tLimitOverrunError\n",
      "\tQueueEmpty\n",
      "\tQueueFull\n",
      "\terror\n",
      "\tLZMAError\n",
      "\tRegistryError\n",
      "\t_GiveupOnFastCopy\n",
      "\tEmpty\n",
      "\tFull\n",
      "\tZMQBaseError\n",
      "\t\tZMQError\n",
      "\t\tZMQBindError\n",
      "\t\tNotDone\n",
      "\tPickleError\n",
      "\t\tPicklingError\n",
      "\t\tUnpicklingError\n",
      "\t_Stop\n",
      "\tArgumentError\n",
      "\tArgumentTypeError\n",
      "\tConfigError\n",
      "\t\tConfigLoaderError\n",
      "\t\tConfigFileNotFound\n",
      "\tConfigurableError\n",
      "\t\tMultipleInstanceError\n",
      "\tApplicationError\n",
      "\tTimeoutError\n",
      "\tCOMError\n",
      "\tArgumentError\n",
      "\tReturnValueIgnoredError\n",
      "\tKeyReuseError\n",
      "\tUnknownKeyError\n",
      "\tLeakedCallbackError\n",
      "\tBadYieldError\n",
      "\tReturnValueIgnoredError\n",
      "\tReturn\n",
      "\tInvalidPortNumber\n",
      "\tNoIPAddresses\n",
      "\tBadZipFile\n",
      "\tLargeZipFile\n",
      "\tError\n",
      "\t\tNoSectionError\n",
      "\t\tDuplicateSectionError\n",
      "\t\tDuplicateOptionError\n",
      "\t\tNoOptionError\n",
      "\t\tInterpolationError\n",
      "\t\tParsingError\n",
      "\tBadEntryPoint\n",
      "\tNoSuchEntryPoint\n",
      "\tDuplicateKernelError\n",
      "\tErrorDuringImport\n",
      "\tBdbQuit\n",
      "\tRestart\n",
      "\tFindCmdError\n",
      "\tHomeDirError\n",
      "\tProfileDirError\n",
      "\tIPythonCoreError\n",
      "\t\tTryNext\n",
      "\t\tUsageError\n",
      "\t\tStdinNotImplementedError\n",
      "\tInputRejected\n",
      "\tGetoptError\n",
      "\tOptionError\n",
      "\tErrorToken\n",
      "\tPrefilterError\n",
      "\tAliasError\n",
      "\t\tInvalidAliasError\n",
      "\tError\n",
      "\t\tInterfaceError\n",
      "\t\tDatabaseError\n",
      "\tWarning\n",
      "\tSpaceInInput\n",
      "\tDOMException\n",
      "\t\tIndexSizeErr\n",
      "\t\tDomstringSizeErr\n",
      "\t\tHierarchyRequestErr\n",
      "\t\tWrongDocumentErr\n",
      "\t\tInvalidCharacterErr\n",
      "\t\tNoDataAllowedErr\n",
      "\t\tNoModificationAllowedErr\n",
      "\t\tNotFoundErr\n",
      "\t\tNotSupportedErr\n",
      "\t\tInuseAttributeErr\n",
      "\t\tInvalidStateErr\n",
      "\t\tSyntaxErr\n",
      "\t\tInvalidModificationErr\n",
      "\t\tNamespaceErr\n",
      "\t\tInvalidAccessErr\n",
      "\t\tValidationErr\n",
      "\tValidationError\n",
      "\tEditReadOnlyBuffer\n",
      "\t_Retry\n",
      "\tInvalidLayoutError\n",
      "\tHeightIsUnknownError\n",
      "\tParserSyntaxError\n",
      "\tInternalParseError\n",
      "\t_PositionUpdatingFinished\n",
      "\tSimpleGetItemNotFound\n",
      "\tUncaughtAttributeError\n",
      "\tHasNoContext\n",
      "\tParamIssue\n",
      "\t_JediError\n",
      "\t\tInternalError\n",
      "\t\tWrongVersion\n",
      "\t\tRefactoringError\n",
      "\tOnErrorLeaf\n",
      "\tInvalidPythonEnvironment\n",
      "\tMessageError\n",
      "\t\tMessageParseError\n",
      "\t\tMultipartConversionError\n",
      "\t\tCharsetError\n",
      "\tError\n",
      "\tHTTPException\n",
      "\t\tNotConnected\n",
      "\t\tInvalidURL\n",
      "\t\tUnknownProtocol\n",
      "\t\tUnknownTransferEncoding\n",
      "\t\tUnimplementedFileMode\n",
      "\t\tIncompleteRead\n",
      "\t\tImproperConnectionState\n",
      "\t\tBadStatusLine\n",
      "\t\tLineTooLong\n",
      "\tInteractivelyDefined\n",
      "\tKillEmbedded\n",
      "\tError\n",
      "\t\tNoSuchProcess\n",
      "\t\tAccessDenied\n",
      "\t\tTimeoutExpired\n",
      "\tError\n",
      "\tTimeoutExpired\n",
      "\tTimeoutAbandoned\n",
      "\tQueueEmpty\n",
      "\tQueueFull\n",
      "\tExpatError\n",
      "\tError\n",
      "\t\tProtocolError\n",
      "\t\tResponseError\n",
      "\t\tFault\n",
      "\terror\n",
      "\tcom_error\n",
      "\tinternal_error\n",
      "\tParseBaseException\n",
      "\t\tParseException\n",
      "\t\tParseFatalException\n",
      "\tRecursiveGrammarException\n",
      "\tResolutionError\n",
      "\t\tVersionConflict\n",
      "\t\tDistributionNotFound\n",
      "\t\tUnknownExtra\n",
      "\tUnableToResolveVariableException\n",
      "\tInvalidTypeInArgsException\n"
     ]
    }
   ],
   "source": [
    "print_exception_hierarchy()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "e4a1f8cb",
   "metadata": {},
   "outputs": [
    {
     "ename": "ZeroDivisionError",
     "evalue": "division by zero",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mZeroDivisionError\u001b[0m                         Traceback (most recent call last)",
      "\u001b[1;32m~\\AppData\\Local\\Temp\\ipykernel_21004\\2983751119.py\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m      3\u001b[0m \u001b[0mx\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;36m5\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      4\u001b[0m \u001b[0my\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;36m0\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 5\u001b[1;33m \u001b[0mz\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mx\u001b[0m\u001b[1;33m/\u001b[0m\u001b[0my\u001b[0m \u001b[1;31m# ZeroDivisionError: division by zero\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[1;31mZeroDivisionError\u001b[0m: division by zero"
     ]
    }
   ],
   "source": [
    "#ANSWER 3-\n",
    "\n",
    "x = 5\n",
    "y = 0\n",
    "z = x/y # ZeroDivisionError: division by zero\n",
    "\"\"\"\n",
    "ZeroDivisionError: This error occurs when you try to divide a number by zero\n",
    "\"\"\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "97866e5a",
   "metadata": {},
   "outputs": [
    {
     "ename": "ValueError",
     "evalue": "math domain error",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "\u001b[1;32m~\\AppData\\Local\\Temp\\ipykernel_21004\\409771840.py\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[1;32mimport\u001b[0m \u001b[0mmath\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 2\u001b[1;33m \u001b[0ma\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mmath\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0msqrt\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m-\u001b[0m\u001b[1;36m1\u001b[0m\u001b[1;33m)\u001b[0m  \u001b[1;31m# ValueError: math domain error\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m      3\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mValueError\u001b[0m: math domain error"
     ]
    }
   ],
   "source": [
    "import math\n",
    "a = math.sqrt(-1)  # ValueError: math domain error\n",
    "\"\"\"\n",
    "FloatingPointError: This error occurs when a floating-point operation fails to produce a valid result.\n",
    "\"\"\"\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "8c5034f4",
   "metadata": {},
   "outputs": [
    {
     "ename": "KeyError",
     "evalue": "'d'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mKeyError\u001b[0m                                  Traceback (most recent call last)",
      "\u001b[1;32m~\\AppData\\Local\\Temp\\ipykernel_21004\\3145945860.py\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m      9\u001b[0m \"\"\"\n\u001b[0;32m     10\u001b[0m \u001b[0mmy_dict\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;33m{\u001b[0m\u001b[1;34m'a'\u001b[0m\u001b[1;33m:\u001b[0m \u001b[1;36m1\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;34m'b'\u001b[0m\u001b[1;33m:\u001b[0m \u001b[1;36m2\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;34m'c'\u001b[0m\u001b[1;33m:\u001b[0m \u001b[1;36m3\u001b[0m\u001b[1;33m}\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 11\u001b[1;33m \u001b[0mvalue\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mmy_dict\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;34m'd'\u001b[0m\u001b[1;33m]\u001b[0m  \u001b[1;31m# KeyError: 'd'\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     12\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     13\u001b[0m \"\"\"\n",
      "\u001b[1;31mKeyError\u001b[0m: 'd'"
     ]
    }
   ],
   "source": [
    "#ANSWER 4-\n",
    "\"\"\"\n",
    "The LookupError class is a subclass of the built-in Exception class in Python. It is used to handle errors that occur when a key or index is not found in a collection or mapping object.\n",
    "\n",
    "Two common exceptions that inherit from LookupError are KeyError and IndexError.\n",
    "\n",
    "KeyError: This error occurs when you try to access a dictionary key that does not exist. For example:\n",
    "\n",
    "\"\"\"\n",
    "my_dict = {'a': 1, 'b': 2, 'c': 3}\n",
    "value = my_dict['d']  # KeyError: 'd'\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "2476ded5",
   "metadata": {},
   "outputs": [
    {
     "ename": "IndexError",
     "evalue": "list index out of range",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mIndexError\u001b[0m                                Traceback (most recent call last)",
      "\u001b[1;32m~\\AppData\\Local\\Temp\\ipykernel_21004\\295553915.py\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m      3\u001b[0m \"\"\"\n\u001b[0;32m      4\u001b[0m \u001b[0mmy_list\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;33m[\u001b[0m\u001b[1;36m1\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;36m2\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;36m3\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 5\u001b[1;33m \u001b[0mvalue\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mmy_list\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;36m3\u001b[0m\u001b[1;33m]\u001b[0m  \u001b[1;31m# IndexError: list index out of range\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m      6\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      7\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mIndexError\u001b[0m: list index out of range"
     ]
    }
   ],
   "source": [
    "\"\"\"\n",
    "IndexError: This error occurs when you try to access a list or tuple index that is out of range. For example:\n",
    "\"\"\"\n",
    "my_list = [1, 2, 3]\n",
    "value = my_list[3]  # IndexError: list index out of range\n",
    "\n",
    "\n",
    "\"\"\"\n",
    "Both KeyError and IndexError are subclasses of LookupError, because they represent a failure to look up an item in a collection or mapping object. By inheriting from LookupError, these exceptions can be caught together using a single except block:\n",
    "\n",
    "\"\"\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f2694ff0",
   "metadata": {},
   "outputs": [],
   "source": [
    "#ANSWER 5-\n",
    "\n",
    "\"\"\"ImportError is a built-in Python exception that is raised when an imported module, package, or name cannot be found or loaded during the execution of a Python script or module.\n",
    "This can happen if the module, package, or name is misspelled, if the module is not installed in the Python environment, if the module is located in the wrong directory, or if there \n",
    "are version conflicts between different modules.\n",
    "\n",
    "ModuleNotFoundError is a subclass of ImportError that was introduced in Python 3.6. It is raised specifically when a module or package is not found during an import statement. \n",
    "This exception is meant to make it easier for developers to diagnose and fix import errors, as it provides a more informative error message that includes the name of the missing \n",
    "module or package.\"\"\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5d13580d",
   "metadata": {},
   "outputs": [],
   "source": [
    "#ANSWER 6-\n",
    "\n",
    "\"\"\"\n",
    "Here are some best practices for exception handling in Python:\n",
    "\n",
    "1-Catch specific exceptions: Catch only the exceptions that you expect and can handle. This makes it easier to understand and maintain the code. Catching broad exceptions like Exception can mask errors and make debugging more difficult.\n",
    "\n",
    "2-Use the try-except-else block: Use the try-except-else block to catch and handle exceptions. The else block is executed if no exception is raised, and is useful for cleaning up resources or performing additional operations after the try block.\n",
    "\n",
    "3-Use the finally block for cleanup: Use the finally block to perform cleanup operations such as closing files, releasing resources, or restoring the state of the program. The finally block is executed regardless of whether an exception was raised or not.\n",
    "\n",
    "4-Log exceptions: Log exceptions using a logging framework like logging or loguru. This can help in debugging and identifying the root cause of the error.\n",
    "\n",
    "5-Raise exceptions with informative messages: When raising an exception, include an informative message that explains the cause of the error. This can help in debugging and fixing the issue.\n",
    "\"\"\"\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
